feature: RTL support added
fluidweb-co/fluid-checkout pull request #4
Opened 2022-02-16 20:01 UTC by alamgircsebd

2022-02-17 14:50 UTC, diegoversiani commented
@alamgircsebd, thank you for improving the WooCommece checks and activation links.

There are a few general issues with this PR:

- the style files (`.scss`) should always be split into partial files
- compiled `css/*.css` and `js/*.js` files need to be committed, they are ignored during the PR review, however, they are needed for the plugin to work properly.
- pixel values need to be wrapped with the `remsize()` sass function, this allows theme developers to rebuild the styles using `rem` size units if needed.

2022-02-17 14:57 UTC, diegoversiani commented
@alamgircsebd, I think we can change some styles definitions from `left` to `right` and vice versa using SASS value interpolation.

This could potentially avoid the creation of new RTL files for each partial, for each theme or plugin we have compatibility with.

For example, instead of this as a separate RTL file:

```scss
form.woocommerce-checkout .fc-wrapper #order_review table.woocommerce-checkout-review-order-table .product-quantity {
    right: 65px;
    left: auto;
    transform: translateX(100%) translateY(-25%);
}
```

We could do this in the original partial file:

```scss
form.woocommerce-checkout .fc-wrapper #order_review table.woocommerce-checkout-review-order-table .product-quantity {
    #{ $horizontal-position }: 65px;
    transform: translateX(100%) translateY(-25%);
}
```

For that, we need to identify the CSS properties that change from LTR to RTL and change all original partial files to support the new variables.

Then, to generate separate styles for RTL, we can import all the same partials but change the variables.

2022-02-20 18:41 UTC, alamgircsebd commented
> @alamgircsebd, I think we can change some styles definitions from `left` to `right` and vice versa using SASS value interpolation.
> 
> This could potentially avoid the creation of new RTL files for each partial, for each theme or plugin we have compatibility with.
> 
> For example, instead of this as a separate RTL file:
> 
> ```css-scss
> form.woocommerce-checkout .fc-wrapper #order_review table.woocommerce-checkout-review-order-table .product-quantity {
>     right: 65px;
>     left: auto;
>     transform: translateX(100%) translateY(-25%);
> }
> ```
> 
> We could do this in the original partial file:
> 
> ```css-scss
> form.woocommerce-checkout .fc-wrapper #order_review table.woocommerce-checkout-review-order-table .product-quantity {
>     #{ $horizontal-position }: 65px;
>     transform: translateX(100%) translateY(-25%);
> }
> ```
> 
> For that, we need to identify the CSS properties that change from LTR to RTL and change all original partial files to support the new variables.
> 
> Then, to generate separate styles for RTL, we can import all the same partials but change the variables.

please review now

2022-02-22 01:07 UTC, diegoversiani requested changes

2022-02-22 01:07 UTC, diegoversiani commented on sass/checkout-layout-rtl.scss
> +    right: auto !important;
@alamgircsebd High level `.scss` files should not contain code that generates CSS directly, only imports for necessary abstract files and partial files are permitted.

Move the new code to the appropriate existing partial files, or create new partial files for it.

2022-02-22 01:07 UTC, diegoversiani commented on sass/checkout-layout-rtl.scss
> +    right: 0px;
@alamgircsebd avoid the use of size unit when value is `0`.

2022-02-22 01:07 UTC, diegoversiani commented on sass/checkout-layout-rtl.scss
> +    right: auto !important;
@alamgircsebd Replace `px` with `remsize()`, and use new alignment variables for this code.

2022-02-22 01:07 UTC, diegoversiani commented on sass/partials/_order-summary.scss
> +	margin-right: $wc-checkout-review-order-table-img;// -8px;
@alamgircsebd keep various `margin` properties together at the top.

2022-02-22 01:07 UTC, diegoversiani commented on sass/partials/_order-summary.scss
> +	//padding-left: $global-spacing-small;
@alamgircsebd remove commented code.

2022-02-22 21:12 UTC, alamgircsebd commented
Review now

2022-02-23 07:48 UTC, diegoversiani commented
@alamgircsebd there are various layout issues with the RTL version, I'm using the default WooCommerce Storefront theme. See the images attached.

![Screen Shot 2022-02-23 at 08 27 01](https://user-images.githubusercontent.com/17417563/155279021-f5902edf-db1f-461c-a5fd-70cc85b3457c.png)
![Screen Shot 2022-02-23 at 08 27 29](https://user-images.githubusercontent.com/17417563/155279024-56563aad-a1ab-4c4c-91e4-81028c923f71.png)
![Screen Shot 2022-02-23 at 08 28 18](https://user-images.githubusercontent.com/17417563/155279025-4e94958f-9c31-4b23-b003-11debddd3beb.png)
![Screen Shot 2022-02-23 at 08 32 28](https://user-images.githubusercontent.com/17417563/155279027-7ab75e86-3a91-4645-90b6-2ee4a5aa459c.png)
![Screen Shot 2022-02-23 at 08 34 47](https://user-images.githubusercontent.com/17417563/155279029-c5902ee6-b5bc-499f-bb57-fbfd1896ec08.png)
![Screen Shot 2022-02-23 at 08 25 25](https://user-images.githubusercontent.com/17417563/155279031-413aaea5-8dfd-4ffd-bbd2-ed000e1e8a89.png)
![Screen Shot 2022-02-23 at 08 30 40](https://user-images.githubusercontent.com/17417563/155279034-7a9bb5ac-1e2a-4fd5-8ea1-37210c0df547.png)
![Screen Shot 2022-02-23 at 08 39 47](https://user-images.githubusercontent.com/17417563/155279035-6f496839-bdac-418d-8260-ce3d3030cf70.png)

2022-02-25 20:28 UTC, alamgircsebd commented
Review now

2022-02-26 06:57 UTC, diegoversiani commented
@alamgircsebd There are still things that were not addressed, please check all the (pending) comments in the code "files changed" tab.

Also, check other layout issues in the screenshots below:

<img width="624" alt="Screen Shot 2022-02-26 at 06 58 55" src="https://user-images.githubusercontent.com/17417563/155833359-374fbc8d-5486-4f52-804d-62e5c6bc0fa8.png">
<img width="507" alt="Screen Shot 2022-02-26 at 07 02 29" src="https://user-images.githubusercontent.com/17417563/155833361-42410aad-c0f4-4634-b2de-296233b2c6c4.png">
<img width="466" alt="Screen Shot 2022-02-26 at 07 02 52" src="https://user-images.githubusercontent.com/17417563/155833363-e01bf5c5-a544-4930-ae49-29abf8e76610.png">
<img width="654" alt="Screen Shot 2022-02-26 at 07 34 27" src="https://user-images.githubusercontent.com/17417563/155833369-ddb58e4a-c8dd-4cea-9415-4e461aae5614.png">
<img width="595" alt="Screen Shot 2022-02-26 at 07 31 46" src="https://user-images.githubusercontent.com/17417563/155833370-7f39a033-cc20-4ee1-ad08-86d968b95efc.png">
<img width="510" alt="Screen Shot 2022-02-26 at 07 04 34" src="https://user-images.githubusercontent.com/17417563/155833371-3108f932-a261-4ca3-bf13-25c8a84c52e5.png">

2022-02-28 09:32 UTC, merged