Conflicting with paypal setting issue fixed
fluidweb-co/fluid-checkout pull request #5
Opened 2022-02-20 19:24 UTC by alamgircsebd

2022-02-22 01:08 UTC, diegoversiani requested changes

2022-02-22 20:41 UTC, alamgircsebd commented on inc/checkout-validation.php
> +		}
Resolved

2022-02-22 20:41 UTC, alamgircsebd commented on inc/checkout-hide-optional-fields.php
> +		}
Resolved

2022-02-23 06:59 UTC, diegoversiani approved these changes

2022-02-23 06:59 UTC, merged